### ISSUE TITLE
bug: IAM Controller keeps re-reconciling Role resources when `InlinePolicies` is not specified.

### ISSUE THREAD

**Issue by wjf3121** [aws-controllers-k8s/community#1939]
**Describe the bug**
We use [controller-runtime client](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) to create Role resources through IAM Controller. When the `InlinePolicies` is not specified in the spec, the IAM Controller will keep re-reconciling  the resource even though there's no real diff.

Checking the IAM Controller log, it keeps reporting the following message:
```
{"level":"info","ts":"2023-11-14T03:58:30.547Z","logger":"ackrt","msg":"desired resource state has changed","account":"xxxxxxxxx","role":"","region":"ap-southeast-1","kind":"Role","namespace":"xxxxxxxxxx","name":"test-role","is_adopted":false,"generation":3,"diff":[{"Path":{"Parts":["Spec","InlinePolicies"]},"A":null,"B":{}}]}
```

**Steps to reproduce**

The following Go snippet can reproduce this issue:
```go
// InlinePolicies is not specified.
role := &ackiamv1alpha1.Role{
		ObjectMeta: metav1.ObjectMeta{
			Name:     "test-role",
			Namespace: "default",
		},
		Spec: ackiamv1alpha1.RoleSpec{
			AssumeRolePolicyDocument: &assumeRolePolicyDocument,
			Name:                     &option.RoleName,
			PolicyRefs:               policyRefs,
			Tags:                     tags,
		},
	}

// kc is a controller-runtime client
// https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client
kc.Create(ctx, role)


```

**Expected outcome**
There should be no diff to reconciling when InlinePolicies is not specified.

**Environment**

* Kubernetes version: 1.26
* Using EKS (yes), 1.26
* AWS service targeted (S3, RDS, etc.): IAM
*  IAM Controller: 1.3.0

**Comment by wjf3121** [comment]
@a-hilaly Thanks for taking this issue! 

Do you have a ETA for the fix? This issue together with https://github.com/aws-controllers-k8s/iam-controller/pull/85 is blocking us from upgrading the IAM controller from `v1.2.1` because we rely on the status `ACK.ResourceSynced` to check whether the resource is in sync or not.

**Comment by a-hilaly** [comment]
I'm debugging this issue. If the fix is simple i'll try to ship it with https://github.com/aws-controllers-k8s/iam-controller/pull/85 .Otherwise i'll do it in a different PR

**Comment by a-hilaly** [comment]
Opened https://github.com/aws-controllers-k8s/community/issues/1941 which is the ideal fix for this problem, but we could definitely customize something for iam-controller for now

**Comment by a-hilaly** [comment]
@wjf3121 Did you trying setting the `InlinePolicies` to an empty map? I believe this could resolve your issue for now. 
```go
// InlinePolicies is not specified.
role := &ackiamv1alpha1.Role{
		ObjectMeta: metav1.ObjectMeta{
			Name:     "test-role",
			Namespace: "default",
		},
		Spec: ackiamv1alpha1.RoleSpec{
			AssumeRolePolicyDocument: &assumeRolePolicyDocument,
			Name:                     &option.RoleName,
			PolicyRefs:               policyRefs,
			Tags:                     tags,
                        InlinePolicies:           map[string]*string{}
		},
	}

// kc is a controller-runtime client
// https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client
kc.Create(ctx, role)
```

**Comment by wjf3121** [comment]
Hi @a-hilaly , yes, we did. Unfortunately an empty map still triggers the issue -- my guess is the empty map will be omitted when the struct is sent to API server, serialized to JSON.

**Comment by wjf3121** [comment]
Hi @a-hilaly, is there any update to this issue? If you can think of any possible work-around before a fix can land I can give it a try. I tried to create a no-op inline policy but failed to do so, feel free to let me know if you know how to achieve this. Thanks!

**Comment by a-hilaly** [comment]
Hi @wjf3121 - I opened https://github.com/aws-controllers-k8s/code-generator/pull/475 to fix the generated code that is causing this issue, and it looks like the `iam-controller` is not experiencing this issue anymore. I still need to fix the unit tests and regenerate all the controllers... i'll make sure iam-controller is one of the first to receive the release.

For a work around, i don't think it's possible since you're using client-go Go types with `omitempty` tag directives.. Maybe switching to dynamic client and/or using `unstructured.Unstructured` could help here.

**Comment by wjf3121** [comment]
Thanks @a-hilaly! Do you have an ETA for https://github.com/aws-controllers-k8s/code-generator/pull/475? Asking because if it can be merged soon we'd prefer not using any of these workaround.

**Comment by a-hilaly** [comment]
@wjf3121 I just fixed the unit tests in the https://github.com/aws-controllers-k8s/code-generator/pull/475 - expecting to make a release wave for all the controllers sometimes this weeks. You can follow the thread here for me info https://kubernetes.slack.com/archives/C0402D8JJS1/p1702061893337749

**Comment by alexanderccc** [comment]
I might be wrong, but looking at the latest release for the IAM controller, I see the code-generator being updated `code-generator v0.28.0`

Rolled out v1.3.2 and even though the logs don't show the reconciliation happening, I still see the resourceVersion being updated on the Role resources, as well as the `lastTransitionTime` under status.conditions. 

Could this be due to the configuration of the controller/Role or is the update still pending?

**Comment by a-hilaly** [comment]
>I still see the resourceVersion being updated on the Role resources, as well as the lastTransitionTime under status.conditions.

@alexanderccc  Is this happening frequently, or did it only happen once? Are there any logs, state that the resources is being reconciled?


> Could this be due to the configuration of the controller/Role or is the update still pending?

The patch started helping to controller to avoid making "Update" calls in case of unchanged `inlinePolicies`. If the resourceVersion is changing, it must something else.

**Comment by alexanderccc** [comment]
@a-hilaly It's happening quite frequently, but I can only see any activity when debug logging is enabled. Might not be related to this issue though as I've removed the inlinePolicies and I still see the same, here are the logs from what it's doing.

1st log execution

```
{"level":"debug","ts":"2023-12-19T02:10:18.624Z","logger":"ackrt","msg":"> r.Sync","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.624Z","logger":"ackrt","msg":">> r.resetConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.624Z","logger":"ackrt","msg":"<< r.resetConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.624Z","logger":"ackrt","msg":">> rm.ResolveReferences","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.629Z","logger":"ackrt","msg":"<< rm.ResolveReferences","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.629Z","logger":"ackrt","msg":">> rm.EnsureTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.629Z","logger":"ackrt","msg":"<< rm.EnsureTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.629Z","logger":"ackrt","msg":">> rm.ReadOne","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.629Z","logger":"ackrt","msg":">>> rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.656Z","logger":"ackrt","msg":">>>> rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.685Z","logger":"ackrt","msg":"<<<< rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.686Z","logger":"ackrt","msg":">>>> rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.701Z","logger":"ackrt","msg":"<<<< rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.701Z","logger":"ackrt","msg":">>>> rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":"<<<< rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":"<<< rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":"<< rm.ReadOne","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":">> r.updateResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":"<< r.updateResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":">> r.lateInitializeResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":">>> rm.LateInitialize","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.726Z","logger":"ackrt","msg":">>>> rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.767Z","logger":"ackrt","msg":">>>>> rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.784Z","logger":"ackrt","msg":"<<<<< rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.784Z","logger":"ackrt","msg":">>>>> rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.810Z","logger":"ackrt","msg":"<<<<< rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.810Z","logger":"ackrt","msg":">>>>> rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"<<<<< rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"<<<< rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"<<< rm.LateInitialize","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"error":""}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":">>> r.patchResourceMetadataAndSpec","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"no difference found between metadata and spec for desired and latest object.","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"<<< r.patchResourceMetadataAndSpec","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"<< r.lateInitializeResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"error":""}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":">> r.ensureConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"<< r.ensureConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"< r.Sync","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"error":""}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":"> r.patchResourceStatus","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":">> kc.Patch (status)","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.847Z","logger":"ackrt","msg":"patched resource status","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"json":"{\"metadata\":{\"resourceVersion\":\"234473637\"},\"spec\":{\"policies\":null},\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2023-12-19T02:10:18Z\",\"status\":\"True\",\"type\":\"ACK.ReferencesResolved\"},{\"lastTransitionTime\":\"2023-12-19T02:10:18Z\",\"message\":\"Late initialization did not complete, requeuing with delay of 5 seconds\",\"reason\":\"Delayed Late Initialization\",\"status\":\"False\",\"type\":\"ACK.LateInitialized\"},{\"lastTransitionTime\":\"2023-12-19T02:10:18Z\",\"status\":\"False\",\"type\":\"ACK.ResourceSynced\"}]}}"}
{"level":"debug","ts":"2023-12-19T02:10:18.847Z","logger":"ackrt","msg":"<< kc.Patch (status)","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.847Z","logger":"ackrt","msg":"< r.patchResourceStatus","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:10:18.847Z","logger":"ackrt","msg":"requeueing","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"after":5}
{"level":"debug","ts":"2023-12-19T02:10:18.851Z","logger":"exporter.field-export-reconciler","msg":"error did not need requeue","error":"the source resource is not synced yet"}
```

some other log execution

```
{"level":"debug","ts":"2023-12-19T02:15:05.492Z","logger":"ackrt","msg":"> r.Sync","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.492Z","logger":"ackrt","msg":">> r.resetConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.492Z","logger":"ackrt","msg":"<< r.resetConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.492Z","logger":"ackrt","msg":">> rm.ResolveReferences","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.496Z","logger":"ackrt","msg":"<< rm.ResolveReferences","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.496Z","logger":"ackrt","msg":">> rm.EnsureTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.496Z","logger":"ackrt","msg":"<< rm.EnsureTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.496Z","logger":"ackrt","msg":">> rm.ReadOne","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.496Z","logger":"ackrt","msg":">>> rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.529Z","logger":"ackrt","msg":">>>> rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.559Z","logger":"ackrt","msg":"<<<< rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.559Z","logger":"ackrt","msg":">>>> rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.575Z","logger":"ackrt","msg":"<<<< rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.575Z","logger":"ackrt","msg":">>>> rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":"<<<< rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":"<<< rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":"<< rm.ReadOne","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":">> r.updateResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":"<< r.updateResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":">> r.lateInitializeResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":">>> rm.LateInitialize","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.602Z","logger":"ackrt","msg":">>>> rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.645Z","logger":"ackrt","msg":">>>>> rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.661Z","logger":"ackrt","msg":"<<<<< rm.getManagedPolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.661Z","logger":"ackrt","msg":">>>>> rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.679Z","logger":"ackrt","msg":"<<<<< rm.getInlinePolicies","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.679Z","logger":"ackrt","msg":">>>>> rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"<<<<< rm.getTags","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"<<<< rm.sdkFind","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"<<< rm.LateInitialize","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"error":""}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":">>> r.patchResourceMetadataAndSpec","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"no difference found between metadata and spec for desired and latest object.","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"<<< r.patchResourceMetadataAndSpec","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"<< r.lateInitializeResource","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"error":""}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":">> r.ensureConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"<< r.ensureConditions","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.697Z","logger":"ackrt","msg":"< r.Sync","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"error":""}
{"level":"debug","ts":"2023-12-19T02:15:05.698Z","logger":"ackrt","msg":"> r.patchResourceStatus","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.698Z","logger":"ackrt","msg":">> kc.Patch (status)","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.708Z","logger":"ackrt","msg":"patched resource status","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"json":"{\"metadata\":{\"resourceVersion\":\"234477383\"},\"spec\":{\"policies\":null},\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2023-12-19T02:15:05Z\",\"status\":\"True\",\"type\":\"ACK.ReferencesResolved\"},{\"lastTransitionTime\":\"2023-12-19T02:15:05Z\",\"message\":\"Late initialization did not complete, requeuing with delay of 5 seconds\",\"reason\":\"Delayed Late Initialization\",\"status\":\"False\",\"type\":\"ACK.LateInitialized\"},{\"lastTransitionTime\":\"2023-12-19T02:15:05Z\",\"status\":\"False\",\"type\":\"ACK.ResourceSynced\"}]}}"}
{"level":"debug","ts":"2023-12-19T02:15:05.708Z","logger":"ackrt","msg":"<< kc.Patch (status)","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.708Z","logger":"ackrt","msg":"< r.patchResourceStatus","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
{"level":"debug","ts":"2023-12-19T02:15:05.708Z","logger":"ackrt","msg":"requeueing","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2,"after":5}
{"level":"debug","ts":"2023-12-19T02:15:05.731Z","logger":"exporter.field-export-reconciler","msg":"error did not need requeue","error":"the source resource is not synced yet"}
```

Will investigate some more and might open another issue for this.

**Comment by a-hilaly** [comment]
>{"level":"debug","ts":"2023-12-19T02:10:18.824Z","logger":"ackrt","msg":">> kc.Patch (status)","account":"**account**","role":"","region":"**region**","kind":"Role","namespace":"**namespace**","name":"**name**","is_adopted":false,"generation":2}
I believe the status patch is causing the conditions to be updated.. which is quiet normal. 

Can you share a yaml sample of the resource you're trying to deploy? i believe this could be related to the late-initialization of the "description" field

**Comment by wjf3121** [comment]
Hi @a-hilaly, the issue is gone after we deployed the latest version of IAM controller, thanks for your great effort on this one.

BTW, we are stilling facing this reconciling issue: https://github.com/aws-controllers-k8s/community/issues/1919 (although in this case we have an obvious workaround to set the description to a non empty value.)

**Comment by a-hilaly** [comment]
This is now fixed in [iam-controller v1.3.6](https://github.com/aws-controllers-k8s/iam-controller/releases/tag/v1.3.6) - the controller now correctly handles the Description field for Roles and Policies, preventing an infinite requeue caused by missing Description field in Create calls. cc @widdendream
