### ISSUE TITLE
ACK(Cloudfront) IllegalUpdate: OriginReadTimeout is required for updates

### ISSUE THREAD

**Issue by pankajagarwal** [aws-controllers-k8s/community#2335]
**Describe the bug**
An update to cloudfront origin is forcing me to add all the optional fields to my yaml definition.

IllegalUpdate: OriginReadTimeout is required for updates. Same error for custom header

**Steps to reproduce**

1. Deploy a basic Cloudfront distribution with all defaults.
2. Above step will default the origin to use TLSv1 as the default minimum protocol.
3. Try to change the yaml definition to use TLSv1.2 instead and then updates will fail error as above.

**Expected outcome**
The update should add only the specific change to the definition and update.

**Environment**
Production

* Kubernetes version 1.31
* Using EKS yes 
* AWS service targeted Cloudfront

**Comment by michaelhtm** [comment]
Hey @pankajagarwal, can you provide the manifest you used? I can try to reproduce, thanks

**Comment by pankajagarwal** [comment]
@michaelhtm so i was able to make it work in 1 account and for single distribution as i was developing the template but then when i deployed the same template which is working in 1 account into another one it fails with "InvalidArgument: The parameter MinTTL is required.\n\tstatus code: 400"

basically it's a cloudfront with behavior using **Cache policy and origin request policy (recommended)** and use caching disabled, All Viewers as the option.

here's the distribution with spec failing now (i have removed/modified my domains and certs) ... 

`apiVersion: cloudfront.services.k8s.aws/v1alpha1
kind: Distribution
metadata:
spec:
  distributionConfig:
    aliases:
      items:
      - global.example.net
    cacheBehaviors:
      items:
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /us-east-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: use1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /v3/us-east-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: use1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /us-west-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: usw1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /v3/us-west-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: usw1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /eu-central-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: euc1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /v3/eu-central-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: euc1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
        pathPattern: /ap-northeast-1/*
        responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        smoothStreaming: false
        targetOriginID: apne1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        pathPattern: /v3/ap-northeast-1/*
        smoothStreaming: false
        targetOriginID: apne1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
    comment: global.example.net
    continuousDeploymentPolicyID: ""
    customErrorResponses: {}
    defaultCacheBehavior:
      allowedMethods:
        cachedMethods:
          items:
          - HEAD
          - GET
        items:
        - HEAD
        - GET
        - OPTIONS
      cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
      compress: true
      fieldLevelEncryptionID: ""
      functionAssociations: {}
      lambdaFunctionAssociations: {}
      originRequestPolicyID: 216adef6-5c7f-47e4-b989-5492eafa07d3
      responseHeadersPolicyID: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
      smoothStreaming: false
      targetOriginID: global
      trustedKeyGroups:
        enabled: false
      trustedSigners:
        enabled: false
      viewerProtocolPolicy: redirect-to-https
    defaultRootObject: ""
    enabled: true
    httpVersion: http2and3
    isIPV6Enabled: true
    logging:
      bucket: ""
      enabled: false
      includeCookies: false
      prefix: ""
    originGroups: {}
    origins:
      items:
      - connectionAttempts: 3
        connectionTimeout: 10
        customHeaders: {}
        customOriginConfig:
          httpPort: 80
          httpSPort: 443
          originKeepaliveTimeout: 5
          originProtocolPolicy: https-only
          originReadTimeout: 30
          originSSLProtocols:
            items:
            - TLSv1.2
        domainName: ap-northeast-1.example.net
        id: apne1
        originAccessControlID: ""
        originPath: ""
        originShield:
          enabled: false
      - connectionAttempts: 3
        connectionTimeout: 10
        customHeaders: {}
        customOriginConfig:
          httpPort: 80
          httpSPort: 443
          originKeepaliveTimeout: 5
          originProtocolPolicy: https-only
          originReadTimeout: 30
          originSSLProtocols:
            items:
            - TLSv1.2
        domainName: eu-central-1.example.net
        id: euc1
        originAccessControlID: ""
        originPath: ""
        originShield:
          enabled: false
      - connectionAttempts: 3
        connectionTimeout: 10
        customHeaders: {}
        customOriginConfig:
          httpPort: 80
          httpSPort: 443
          originKeepaliveTimeout: 5
          originProtocolPolicy: https-only
          originReadTimeout: 30
          originSSLProtocols:
            items:
            - TLSv1.2
        domainName: globalb.example.net
        id: global
        originAccessControlID: ""
        originPath: ""
        originShield:
          enabled: false
      - connectionAttempts: 3
        connectionTimeout: 10
        customHeaders: {}
        customOriginConfig:
          httpPort: 80
          httpSPort: 443
          originKeepaliveTimeout: 5
          originProtocolPolicy: https-only
          originReadTimeout: 30
          originSSLProtocols:
            items:
            - TLSv1.2
        domainName: us-east-1.example.net
        id: use1
        originAccessControlID: ""
        originPath: ""
        originShield:
          enabled: false
      - connectionAttempts: 3
        connectionTimeout: 10
        customHeaders: {}
        customOriginConfig:
          httpPort: 80
          httpSPort: 443
          originKeepaliveTimeout: 5
          originProtocolPolicy: https-only
          originReadTimeout: 30
          originSSLProtocols:
            items:
            - TLSv1.2
        domainName: us-west-1.example.net
        id: usw1
        originAccessControlID: ""
        originPath: ""
        originShield:
          enabled: false
    priceClass: PriceClass_All
    restrictions:
      geoRestriction:
        restrictionType: none
    staging: false
    viewerCertificate:
      acmCertificateARN: <valid certificate arm>
      certificate: <valid certificate arm>
      certificateSource: acm
      cloudFrontDefaultCertificate: false
      minimumProtocolVersion: TLSv1.2_2021
      sslSupportMethod: sni-only
    webACLID: ""
`

**Comment by pankajagarwal** [comment]
I upgraded to version 1.0.8 from 1.0.3 considering it's now using aws-sdk-go v2 but not sure if that issue is still there or not.

It's say's resource synced and then also " InvalidArgument: The parameter MinTTL is required."

Can not tell if it's applying the change as i manually applied the change on CDN that were failing before.

Here's the status ..

`  Conditions:
    Last Transition Time:            2025-02-28T20:37:19Z
    Status:                          True
    Type:                            ACK.ResourceSynced
    Message:                         InvalidArgument: The parameter MinTTL is required.
    Status:                          True
    Type:                            ACK.Terminal`

**Comment by pankajagarwal** [comment]
@michaelhtm were you able to look at this and do you have any suggestions here ?

**Comment by michaelhtm** [comment]
Hi @pankajagarwal, i haven't had the chance to take a look

**Comment by michaelhtm** [comment]
So I attempted to reproduce this issue and still unable to do so..
My guess is, the issue is coming from here:
```yaml
      - allowedMethods:
          cachedMethods:
            items:
            - HEAD
            - GET
          items:
          - HEAD
          - GET
          - OPTIONS
        compress: true
        fieldLevelEncryptionID: ""
        functionAssociations: {}
        lambdaFunctionAssociations: {}
        pathPattern: /v3/ap-northeast-1/*
        smoothStreaming: false
        targetOriginID: apne1
        trustedKeyGroups:
          enabled: false
        trustedSigners:
          enabled: false
        viewerProtocolPolicy: redirect-to-https
```
This CacheBehaviour does not contain a cachePolicyID, which then would require a MinTTL according to this: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CacheBehavior.html#cloudfront-Type-CacheBehavior-MinTTL:~:text=Required%3A%20No-,MinTTL,-This%20field%20is

**Comment by pankajagarwal** [comment]
thanks @michaelhtm Indeed it was that as I realized there was a typo in just this section of my helm template.

```
         lambdaFunctionAssociations: {}
         maxTTL: null
         minTTL: null
-        CachePolicyId: {{ .Values.globalcdn.cachepolicyid | quote }}
-        OriginRequestPolicyId: {{ .Values.globalcdn.originrequestpolicyid | quote }}
-        ResponseHeadersPolicyId: {{ .Values.globalcdn.responseheaderpolicyid | quote }}
+        cachePolicyID: {{ .Values.globalcdn.cachepolicyid | quote }}
+        originRequestPolicyID: {{ .Values.globalcdn.originrequestpolicyid | quote }}
+        responseHeadersPolicyID: {{ .Values.globalcdn.responseheaderpolicyid | quote }}
         pathPattern: /v3/ap-northeast-1/*
         smoothStreaming: false
         targetOriginID: apne1

```

After correcting the typo's in the field name, it worked fine.
